apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            default_type text/plain;
            return 200 "{{ .Values.env.name }}";
        }
    }